name: Laravel CI/CD

on:
  push:
    branches:
      - stg
jobs:
  deploy:

    runs-on: [self-hosted, staging-ec2]
    steps:
      - name: Pulling Latest Code
        uses: actions/checkout@v3
        with:
          clean: 'false'

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      
      - name: Install Dependences
        run: |
          composer update && composer install

          
      - name: Clear PHP Cache
        run: php artisan optimize:clear

      - name: Copy and Override Files to /var/www/html
        run: |
          sudo rsync -av . /var/www/html/EduExHub    
