name: Laravel CI/CD

on:
  push:
    branches:
      - stg
jobs:
  deploy:

    runs-on: [self-hosted, staging-vm]
    steps:
      - name: Pulling Latest Code
        uses: actions/checkout@v3
        with:
          clean: 'false'

        
      - name: Use PHP 8
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.2'         

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      
      - name: Install Dependences
        run: |
          composer update && composer install

      - name: Generate Application Key
        run: |
          php artisan key:generate

      - name: Clear PHP Cache
        run: php artisan optimize:clear

      - name: Copy and Override Files to /var/www/html
        run: |
          sudo rsync -a * /var/www/html/EduExHub    
